### ISSUE TITLE
Suppose to work on ZTE GPON ONT?

### ISSUE THREAD

**Issue by stich86** [douniwan5788/zte_modem_tools#2]
Hi,

Is this tool supposed to work on F6XX GPON FTTH ONT?

Decompile httpd daemon there are reference to factorymode/nE%jA@5b but the tool always give bad username/creds.

May be wrong AES key? Looking at the code the AES encode/decode should be done after  entering username and password 

Any idea?

Thx

**Comment by stich86** [comment]
@douniwan5788 i've create [PR#3](https://github.com/douniwan5788/zte_modem_tools/pull/3) that fix the issue on AES version 1

let me know

**Comment by douniwan5788** [comment]
> @douniwan5788 i've create [PR#3](https://github.com/douniwan5788/zte_modem_tools/pull/3) that fix the issue on AES version 1
> 
> let me know

Merged

**Comment by DroidDotThen** [comment]
@stich86 can you pls help me with V9.0.10P18N2B f670l. Unable to open port 23 error is coming

**Comment by douniwan5788** [comment]
> @stich86 can you pls help me with V9.0.10P18N2B f670l. Unable to open port 23 error is coming

please upload your error output

**Comment by DroidDotThen** [comment]
> > @stich86 can you pls help me with V9.0.10P18N2B f670l. Unable to open port 23 error is coming
> 
> please upload your error output

could not open connection to the host, on port 23: connect failed
